/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearsRouteImport } from './routes/years'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoemsIndexRouteImport } from './routes/poems.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as PoemsSlugRouteImport } from './routes/poems.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const YearsRoute = YearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIndexRoute = PoemsIndexRouteImport.update({
  id: '/poems/',
  path: '/poems/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsSlugRoute = PoemsSlugRouteImport.update({
  id: '/poems/$slug',
  path: '/poems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/submit': typeof SubmitRoute
  '/years': typeof YearsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/poems/$slug': typeof PoemsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/poems/': typeof PoemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/submit': typeof SubmitRoute
  '/years': typeof YearsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/poems/$slug': typeof PoemsSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/poems': typeof PoemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/submit': typeof SubmitRoute
  '/years': typeof YearsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/poems/$slug': typeof PoemsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/poems/': typeof PoemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/submit'
    | '/years'
    | '/auth/callback'
    | '/collections/$slug'
    | '/poems/$slug'
    | '/collections/'
    | '/poems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/submit'
    | '/years'
    | '/auth/callback'
    | '/collections/$slug'
    | '/poems/$slug'
    | '/collections'
    | '/poems'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/submit'
    | '/years'
    | '/auth/callback'
    | '/collections/$slug'
    | '/poems/$slug'
    | '/collections/'
    | '/poems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  SubmitRoute: typeof SubmitRoute
  YearsRoute: typeof YearsRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  PoemsSlugRoute: typeof PoemsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  PoemsIndexRoute: typeof PoemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/years': {
      id: '/years'
      path: '/years'
      fullPath: '/years'
      preLoaderRoute: typeof YearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/': {
      id: '/poems/'
      path: '/poems'
      fullPath: '/poems/'
      preLoaderRoute: typeof PoemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/$slug': {
      id: '/poems/$slug'
      path: '/poems/$slug'
      fullPath: '/poems/$slug'
      preLoaderRoute: typeof PoemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  SubmitRoute: SubmitRoute,
  YearsRoute: YearsRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  PoemsSlugRoute: PoemsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  PoemsIndexRoute: PoemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
